{% set name = "esp-caps" %}

{% set version = 1.22 %}
{% set build = 0 %}


package:
  name: "esp-caps"
  version: "{{ version }}"

source:
  fn: ESP122Lin.tgz
  url: https://acdl.mit.edu/ESP/PreBuilts/ESP122Lin.tgz
  sha1: 82871a88a30c396776849657ea1805e28c8685dd
  sha256: c55b1ad93c5521dd2a758c6e86cdfac356943d93898efa78d3a83473b5a01103

build:
  number: 1
  skip: true  # [py<=36]
  string: py{{ CONDA_PY }}_h{{ PKG_HASH }}_{{ build }}
  track_features:

requirements:
  build:
    - python {{ python }}
    - {{ compiler('cxx') }}
    - numpy   1.18   # [py==37]
    - numpy   1.18   # [py==38]
    - numpy   1.19   # [py==39]
    - numpy   1.22   # [py==310]
    - numpy   1.23   # [py==311]
    - make
    - cython
    - setuptools

  host:
    - python {{ python }}
    - pip
    - numpy   1.18   # [py==37]
    - numpy   1.18   # [py==38]
    - numpy   1.19   # [py==39]
    - numpy   1.22   # [py==310]
    - numpy   1.23   # [py==311]
    - cython
    - setuptools
  run:
    - python
    - numpy   1.18   # [py==37]
    - numpy   1.18   # [py==38]
    - numpy   1.19   # [py==39]
    - numpy   1.22   # [py==310]
    - numpy   1.23   # [py==311]

test:
  imports:
    - pyCAPS
    - pyEGADS
    - pyOCSM

about:
  home: https://github.com/sean-engelstad/esp-caps
  license: GNU
  license_family: GPL2
  summary: Parametric CAD Geometry tool
  doc_url: https://acdl.mit.edu/ESP/